export default screen = [
  {name: 'animation scale', screenName: 'ANIMATION-SCALE'},
  {name: 'animation.value', screenName: 'ANIMATION-VALUE'},
  {name: 'animation.Timaing', screenName: 'ANIMATION-TIMAING'},
  {name: 'animation.Trsoalte', screenName: 'ANIMATION-TRSOLATE'},
  {name: 'Fade in, Fade out', screenName: 'ANIMATION-FADEINFADEOUT'},
  {name: 'Fade in, Fade out', screenName: 'PadeIn_PadeOut'},
  {
    name: 'Fade in, Fade out layout anim',
    screenName: 'PadeIn_PadeOut_layoutAnim',
  },
  {name: 'penResponder', screenName: 'penResponder'},
  {name: 'PanResponderReset', screenName: 'PanResponderReset'},
  {name: 'Rotate_animation', screenName: 'Rotate_animation'},
  {name: 'LayotAnimation', screenName: 'LayotAnimation'},
  {name: 'Transolate', screenName: 'Transolate'},
  {name: 'UseNativeDriver', screenName: 'UseNativeDriver'},
  {name: 'Weve_hand', screenName: 'Weve_hand'},
  {name: 'PanhandlerContinuos', screenName: 'PanhandlerContinuos'},
  {name: 'Speedometer', screenName: 'Speedometer'},
  {name: 'panHandelerDecay', screenName: 'panHandelerDecay'},
  {name: 'circulerAnimation', screenName: 'circulerAnimation'},
  {name: 'scrollAnimatedHeader', screenName: 'scrollAnimatedHeader'},
  {name: 'flatlistAnimatedHeader', screenName: 'flatlistAnimatedHeader'},
  {name: 'swiper1', screenName: 'swiper1'},
  {name: 'swiper2', screenName: 'swiper2'},
  {name: 'swiper3', screenName: 'swiper3'},
  {name: 'swiper4', screenName: 'swiper4'},
  {name: 'swiper5', screenName: 'swiper5'},
  {name: 'titleScrolling', screenName: 'titleScrolling'},
  {name: 'animatedScrrolling1', screenName: 'animatedScrrolling1'},
  {name: 'customSwitch', screenName: 'customSwitch'},
  {name: 'pagerButton', screenName: 'pagerButton'},
  {name: 'pageSwiperWithPagerButtonr', screenName: 'SwiperWithPagerButton'},
  {name: 'whatappHeader', screenName: 'whatappHeader'},
  {name: 'headerSearchBar', screenName: 'headerSearchBar'},
  {name: 'animatedItemPopup1', screenName: 'animatedItemPopup1'},
  {name: 'animatedItemPopup2', screenName: 'animatedItemPopup2'},
  {name: 'customScrollView', screenName: 'customScrollView'},
  {name: 'customScrollView2', screenName: 'customScrollView2'},
];
