export default [
  {
    id: '01',
    profile: 'A',
    title: 'Linkedin',
    subtitle: 'Ipsum Lorem do aliquip deserunt voluptate.',
    text: 'Ea officia et aliqua qui irure et eu irure.Ea officia et aliqua qui irure et eu irure.',
    date: '6:40 pm',
    start: '',
  },
  {
    id: '02',
    profile: 'B',
    title: 'Linkedin',
    subtitle: 'Ipsum Lorem do aliquip deserunt voluptate.',
    text: 'Ea officia et aliqua qui irure et eu irure.Ea officia et aliqua qui irure et eu irure.',
    date: '6:40 pm',
    star: '',
  },
  {
    id: '03',
    profile: 'C',
    title: 'Linkedin',
    subtitle: 'Ipsum Lorem do aliquip deserunt voluptate.',
    text: 'Ea officia et aliqua qui irure et eu irure.Ea officia et aliqua qui irure et eu irure.',
    date: '6:40 pm',
    start: '',
  },
  {
    id: '04',
    profile: 'D',
    title: 'Linkedin',
    subtitle: 'Ipsum Lorem do aliquip deserunt voluptate.',
    text: 'Ea officia et aliqua qui irure et eu irure.Ea officia et aliqua qui irure et eu irure.',
    date: '6:40 pm',
    start: '',
  },
  {
    id: '05',
    profile: 'E',
    title: 'Linkedin',
    subtitle: 'Ipsum Lorem do aliquip deserunt voluptate.',
    text: 'Ea officia et aliqua qui irure et eu irure.Ea officia et aliqua qui irure et eu irure.',
    date: '6:40 pm',
    start: '',
  },
  {
    id: '06',
    profile: 'F',
    title: 'Linkedin',
    subtitle: 'Ipsum Lorem do aliquip deserunt voluptate.',
    text: 'Ea officia et aliqua qui irure et eu irure.Ea officia et aliqua qui irure et eu irure.',
    date: '6:40 pm',
    start: '',
  },
  {
    id: '07',
    profile: 'G',
    title: 'Linkedin',
    subtitle: 'Ipsum Lorem do aliquip deserunt voluptate.',
    text: 'Ea officia et aliqua qui irure et eu irure.Ea officia et aliqua qui irure et eu irure.',
    date: '6:40 pm',
    start: '',
  },
  {
    id: '08',
    profile: 'H',
    title: 'Linkedin',
    subtitle: 'Ipsum Lorem do aliquip deserunt voluptate.',
    text: 'Ea officia et aliqua qui irure et eu irure.Ea officia et aliqua qui irure et eu irure.',
    date: '6:40 pm',
    start: '',
  },
  {
    id: '09',
    profile: 'I',
    title: 'Linkedin',
    subtitle: 'Ipsum Lorem do aliquip deserunt voluptate.',
    text: 'Ea officia et aliqua qui irure et eu irure.Ea officia et aliqua qui irure et eu irure.',
    date: '6:40 pm',
    start: '',
  },
  {
    id: '10',
    profile: 'J',
    title: 'Linkedin',
    subtitle: 'Ipsum Lorem do aliquip deserunt voluptate.',
    text: 'Ea officia et aliqua qui irure et eu irure.Ea officia et aliqua qui irure et eu irure.',
    date: '6:40 pm',
    start: '',
  },
];
